[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.backends.legacy:build"

[project]
name = "Hyformer"
version = "1.0.0"
requires-python = "==3.10.*"
dependencies = [
    "numpy>=1.26,<2.0",
    "pandas==1.5.3",
    "rdkit==2023.9.2",
    "scipy==1.10.1",
    "scikit-learn",
    "tqdm",
    "transformers",
    "wandb",
    "torch==2.2.2",
    "torchvision==0.17.2",
    "torchaudio==2.2.2",
    "deepchem==2.8.0",
    "guacamol",
    "fcd==1.2",
]

[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu118" }
torchvision = { index = "pytorch-cu118" }
torchaudio = { index = "pytorch-cu118" }
